cleaning_level:
  LSTCam:
    - 3.5
    - 7.5
    - 2
  NectarCam:
    - 3
    - 5.5
    - 2
  DigiCam:
    - 2
    - 4.5
    - 2

# numPixelInShower:
#   - '>='  # needs to be in quotes because > and ! are special character in yaml
#   - 10
min_num_islands: 8

min_width: 30

min_length: 70

#leakage: 0.6

# leakage2: 0.85
