input_pattern: "*.simtel.gz"
output_suffix: ".hdf5"

overwrite: True

allowed_cameras:
  - LSTCam
  - NectarCam
  - DigiCam

reco_algorithm: planes
integrator : NeighbourPeakIntegrator
cleaning_method: tailcuts_clean

names_to_id:
 LSTCam: 1
 NectarCam: 2
 FlashCam: 3
 DigiCam: 4
 CHEC: 5

types_to_id:
  LST: 1
  MST: 2
  SST: 3

n_events: -1

n_jobs: 1

chunksize: 50

silent: False

verbose: 50

cleaning_level:   ## how do i want to handle different algorrithms needing different paramteers?
  LSTCam:
    - 3.5
    - 7.5
    - 2
  NectarCam:
    - 3
    - 5.5
    - 2
  DigiCam:
    - 2
    - 4.5
    - 2


min_number_of_valid_triggered_cameras: 2