# Fallback if config.yaml is missing values

cleaning_level:
  LSTCam: 
    - 3.5
    - 7.5
    - 2
  NectarCam: 
    - 3
    - 5.5
    - 2
  DigiCam:
    - 2
    - 4.5
    - 2

names_to_id:
 LSTCam: 1
 NectarCam: 2
 FlashCam: 3
 DigiCam: 4
 CHEC: 5

types_to_id:
  LST: 1
  MST: 2
  SST: 3

allowed_cameras: 
  - LSTCam
  - NectarCam
  - DigiCam

n_events: -1

n_jobs: 1

reco_algorithm: planes

overwrite: False

chunksize: 50

silent: False

verbose: 50